"""Add role column to users

Revision ID: 1fdf4c909a02
Revises: 583f5728331f
Create Date: 2026-01-10 14:42:48.346740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdf4c909a02'
down_revision = '583f5728331f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(
            sa.Column('role', sa.String(20), nullable=False, server_default='user')
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
