"""Add username column

Revision ID: 583f5728331f
Revises: 
Create Date: 2026-01-10 14:16:38.310809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583f5728331f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users') as batch_op:
        # 1. Añadir columna nullable
        batch_op.add_column(sa.Column('username', sa.String(120), nullable=True))

    # 2. Rellenar username para usuarios existentes
    conn = op.get_bind()
    users = conn.execute(sa.text("SELECT id, email FROM users")).fetchall()

    for user in users:
        # ejemplo: usar el email antes de la @ como username temporal
        temp_username = user.email.split("@")[0]
        conn.execute(
            sa.text("UPDATE users SET username = :u WHERE id = :id"),
            {"u": temp_username, "id": user.id}
        )

    # 3. Hacer la columna NOT NULL
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('username', nullable=False)

    # 4. Añadir UNIQUE
    with op.batch_alter_table('users') as batch_op:
        batch_op.create_unique_constraint("uq_users_username", ["username"])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
