"""Add thresholds column to users

Revision ID: d03683742af8
Revises: 1fdf4c909a02
Create Date: 2026-01-12 20:35:43.140515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03683742af8'
down_revision = '1fdf4c909a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thresholds', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('thresholds')

    # ### end Alembic commands ###
